start_date: 2023-08-01
end_date: 2023-09-01
initial_cash: 100000.0
strategy_name: PESmallCap
use_cache: true
baseline:
  - sh000300
  - sh000905
universe:
  - sh600000

logging:
  level: INFO
  file_path: results/backtest.log
  console: true

proxy:
  clash_config_path: /mnt/c/Users/10255/.config/clash/config.yaml
  selector_name: "GLOBAL"
