from data_loader.constants import *


CN_CODE = "股票代码"
CN_NAME = "股票名称"
CN_SHORT_CODE = "代码"
CN_SHORT_NAME = "名称"
CN_DATE = "日期"
CN_OPEN = "开盘"
CN_CLOSE = "收盘"
CN_HIGH = "最高"
CN_LOW = "最低"
CN_VOLUME = "成交量"
CN_AMOUNT = "成交额"
CN_TURNOVER_RATE = "换手率"
CN_AMPLITUDE = "振幅"
CN_CHANGE_PCT = "涨跌幅"
CN_CHANGE_AMT = "涨跌额"


# Shareholder surplus constants
CN_CASH_FLOW_STATEMENT = "现金流量表"
CN_INCOME_STATEMENT = "利润表"
CN_ANNUAL_REPORT = "年报"
CN_REPORT_DATE = "报告日"
CN_CASH_FLOW_OPS = "经营活动产生的现金流量净额"
CN_CAPITAL_EXPENDITURE = "购建固定资产、无形资产和其他长期资产支付的现金"
CN_ASSET_IMPAIRMENT = "资产减值损失"
CN_DEPRECIATION = "折旧费"
CN_NET_PROFIT = "净利润"
CN_NET_PROFIT_GROWTH_RATE = "净利润同比增长率"
CN_TOTAL_OPERATING_REVENUE = "营业总收入"
CN_NET_ASSERTS_PER_SHARE = "每股净资产"
CN_REETURN_ON_EQUITY = "净资产收益率"


# Alternative capital expenditure field names
CAPITAL_EXPENDITURE_ALTERNATIVE_1 = "购建固定资产、无形资产和其他长期资产所支付的现金"

# Additional depreciation and impairment fields
FIXED_ASSET_DEPRECIATION = "固定资产折旧"
INTANGIBLE_ASSET_AMORTIZATION = "无形资产摊销"
LONG_TERM_PREPAID_EXPENSES_AMORTIZATION = "长期待摊费用摊销"
INVESTMENT_PROPERTY_DEPRECIATION = "投资性房地产折旧"
CREDIT_IMPAIRMENT_LOSS = "信用减值损失"
OTHER_ASSET_IMPAIRMENT_LOSSES = "其他资产减值损失"


RENAME_DICT = {
    CN_CODE: CODE,
    CN_NAME: NAME,
    CN_SHORT_NAME: NAME,
    CN_SHORT_CODE: CODE,
    CN_DATE: DATE,
    CN_OPEN: OPEN,
    CN_CLOSE: CLOSE,
    CN_HIGH: HIGH,
    CN_LOW: LOW,
    CN_VOLUME: VOLUME,
    CN_AMOUNT: AMOUNT,
    CN_TURNOVER_RATE: TURNOVER_RATE,
    CN_AMPLITUDE: AMPLITUDE,
    CN_CHANGE_PCT: CHANGE_PCT,
    CN_CHANGE_AMT: CHANGE_AMT,
}

FINANCIAL_INDICATORS_RENAME_DICT = {
    CN_REPORT_DATE: REPORT_DATE,
    CN_NET_PROFIT: NET_PROFIT,
    CN_NET_PROFIT_GROWTH_RATE: NET_PROFIT_GROWTH_RATE,
    CN_TOTAL_OPERATING_REVENUE: TOTAL_OPERATING_REVENUE,
    CN_NET_ASSERTS_PER_SHARE: NET_ASSETS_PER_SHARE,
    CN_REETURN_ON_EQUITY: RETURN_ON_EQUITY,
}
